### ISSUE TITLE
Add support for JSON pagination

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-views#16]
Example:

```json
    "_links": {
        "self": {
            "href": "http://example.org/api/user?page=3"
        },
        "first": {
            "href": "http://example.org/api/user"
        },
        "prev": {
            "href": "http://example.org/api/user?page=2"
        },
        "next": {
            "href": "http://example.org/api/user?page=4"
        },
        "last": {
            "href": "http://example.org/api/user?page=133"
        }
    }
```

Using a method such as `hal.paginate(object, total)`

**Comment by ColinHarrington** [comment]
The links are good, but in order to calculate the page numbers we a reference to how many items to render similar to how they do it here: http://phlyrestfully.readthedocs.io/en/latest/halprimer.html#collections

The [&lt;g:paginate&gt; tag](https://github.com/grails/grails-core/blob/master/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/UrlMappingTagLib.groovy#L102) in Grails has a max and offset parameter, but the proposed system here is based on pages.  I think I like the max & offset better than specific pages.  That might be cleaner to translate to GORM and be ultimately more flexible.

**Comment by graemerocher** [comment]
The reference the pages was just an example I copied from somewhere, we should use `max` and `offset` to be consistent with the rest of Grails
