### ISSUE TITLE
Compilation exception when rendering a property called "mappings"

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-views#164]
This view:

```groovy
model {
	Book book
}

def foo = g.render([foo: "bar"] as Object)

json g.render(book) {
	vendor "MyCompany"
	mappings foo
}
```

Fails with:

```
grails.views.ViewException: Error rendering view: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during canonicalization: No such property: name for class: org.codehaus.groovy.ast.expr.PropertyExpression
Possible solutions: safe, type
```

**Comment by alvarosanchez** [comment]
The branch `issue_164` reproduces the issue.

**Comment by alvarosanchez** [comment]
Apparently, `mappings` is being inferred as a property expression of type `Map <String, org.springframework.http.HttpMethod>`

**Comment by AmaliaMV** [comment]
@alvarosanchez I had a similar problem when I wanted to have the word `class`. I solved it by adding quotation marks. `'class' foo`

**Comment by ilopmar** [comment]
The problem with `mappings` being inferred from `org.springframework.http.HttpMethod` is because, by default a "static star import" is added to the compiler here: https://github.com/grails/grails-views/blob/master/core/src/main/groovy/grails/views/ResolvableGroovyTemplateEngine.groovy#L452 and `HttpMethod` is one of the classes defined here: https://github.com/grails/grails-views/blob/master/core/src/main/groovy/grails/views/GenericViewConfiguration.groovy#L82
