### ISSUE TITLE
Documentation: Plugin search locations

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-views#61]
Improve the documentation to include what locations in a plugin will be searched for JSON views.

Per the example can they live anywhere as long as you configure it via the task?

`source = project.file('src/main/gson')`

**Comment by victor-rds** [comment]
+1

Also `inherits template:"parent"` seems to fail when trying to inherit plugin templates, is there any correct nomenclature?

**Comment by jameskleeh** [comment]
I added a test that verifies that works @victor-rds. `/foo/bar.gson` with `inherits template: 'xyz'` will resolve a view with the path `/foo/_xyz.gson` in a plugin.

**Comment by victor-rds** [comment]
@jameskleeh since I modified my project to avoid plugin templates can't say for certain, but I think my problem was a little different, in given time I will text, but I din't use both templates in the same directory.

My was project split in two sub-projects, the first one is a plugin and contains domains, controllers and services common to all of company systems, and second is focused in the business.
Example the first one had a domain class `Employee` and the second has one called `Driver` that extends the first. For the gson, the 1st project I compiled the views, but when tried to use `inherits template:"employee"` on the `_driver.gon` I had no success, I also tried to use the full path with this option but template simply ignores it.

Sorry if this is not the place, since the bug was only about docs
