### ISSUE TITLE
Accept: application/hal+json doesn't work

### ISSUE THREAD

**Issue by NickTheArchitect** [grails/grails-views#64]
I have created a new project using grails 3.2.0.M2. I created a domain class (PolicySet), a controller and generated the views. When I do a GET request to .../policySet/1 with an Accept: header of application/json I get the expected status of 200 and a json body.
Then I added 'hal' to the controller's responseFormats list and created two new views in the policySet folder: show_hal.gson and index_hal.gson.
I expected that a GET request to that same url with an Accept: header of application/hal+json would do the content negotation and return a status of 200 with the defined body from show_hal.gson. The actual result was a status of 406 (NOT_ACCEPTABLE)
I have fixed it in my fork (https://github.com/NickTheArchitect/grails-views/tree/issue-64) by a code change to JsonViewResolver.initialize to add a second default renderer for HAL_JSON.
I don't think this is a complete solution because it needs to be configured by the application if a custom mime type is used, such as `book:     "application/vnd.books.org.book+json"`. In that case a default renderer must be added to the registry for the "book" mime type.

**Comment by jameskleeh** [comment]
So this is covered by http://docs.grails.org/latest/guide/webServices.html#hal

You would have to do as the docs describe to allow rendering of hal. 

For json views, I've added hal rendering by default so that is no longer necessary. In addition, the content types are now configurable. `grails.views.json.mimeTypes`

https://github.com/grails/grails-views/commit/b1f6658aabc7b59287d4157e2ea405887fae551c
